display_name: Ciyue
package_name: ciyue
maintainer:
  name: Mumulhl
  email: mumulhl.666@gmail.com
priority: optional
section: x11
installed_size: 57732
essential: false
icon: assets/icon.png

keywords:
  - Application
  - Dictionary

generic_name: Music Application

categories:
  - Education
  - Languages

startup_notify: true

metainfo: linux/packaging/org.eu.mumulhl.ciyue.metainfo.xml
